name: CTRL
options:
  bundleIdPrefix: com.almatechnologies
  deploymentTarget:
    iOS: "17.0"
  xcodeVersion: "15.0"
settings:
  base:
    INFOPLIST_FILE: Sources/Resources/Info.plist
    PRODUCT_BUNDLE_IDENTIFIER: com.almatechnologies.ctrl
    MARKETING_VERSION: "0.1.0"
    CURRENT_PROJECT_VERSION: "1"
    SWIFT_VERSION: "5.9"
    TARGETED_DEVICE_FAMILY: "2"
    SUPPORTED_INTERFACE_ORIENTATIONS: UIInterfaceOrientationLandscapeLeft UIInterfaceOrientationLandscapeRight
targets:
  CTRL:
    type: application
    platform: iOS
    sources:
      - Sources
    settings:
      base:
        INFOPLIST_FILE: Sources/Resources/Info.plist
