"""initial schema

Revision ID: 9c979fa33d88
Revises: 
Create Date: 2026-04-01 17:03:18.629043

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9c979fa33d88'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('historial',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('timestamp', sa.DateTime(timezone=True), nullable=False),
    sa.Column('usuario', sa.String(length=100), nullable=False),
    sa.Column('tipo_accion', sa.String(length=50), nullable=False),
    sa.Column('entidad_tipo', sa.String(length=50), nullable=False),
    sa.Column('entidad_id', sa.String(length=36), nullable=False),
    sa.Column('descripcion', sa.Text(), nullable=False),
    sa.Column('datos_anteriores', sa.Text(), nullable=True),
    sa.Column('datos_nuevos', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('obras',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('direccion', sa.Text(), nullable=True),
    sa.Column('latitud', sa.Float(), nullable=True),
    sa.Column('longitud', sa.Float(), nullable=True),
    sa.Column('estado', sa.String(length=20), nullable=False),
    sa.Column('tipos_instalacion', sa.Text(), nullable=True),
    sa.Column('carpeta_servidor', sa.Text(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('fecha_inicio', sa.Date(), nullable=True),
    sa.Column('fecha_fin_prevista', sa.Date(), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('operarios',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('especialidades', sa.Text(), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('asignaciones',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('operario_id', sa.String(length=36), nullable=False),
    sa.Column('obra_id', sa.String(length=36), nullable=True),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('es_ruta', sa.Boolean(), nullable=False),
    sa.Column('obras_ruta', sa.Text(), nullable=True),
    sa.Column('latitud_libre', sa.Float(), nullable=True),
    sa.Column('longitud_libre', sa.Float(), nullable=True),
    sa.Column('notas', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=100), nullable=True),
    sa.Column('activo', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.ForeignKeyConstraint(['operario_id'], ['operarios.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('planos',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('obra_id', sa.String(length=36), nullable=False),
    sa.Column('nombre', sa.Text(), nullable=False),
    sa.Column('ruta_original', sa.Text(), nullable=False),
    sa.Column('ruta_anotada', sa.Text(), nullable=True),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('anotado_por', sa.String(length=100), nullable=True),
    sa.Column('anotado_en', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['obra_id'], ['obras.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('planos')
    op.drop_table('asignaciones')
    op.drop_table('operarios')
    op.drop_table('obras')
    op.drop_table('historial')
    # ### end Alembic commands ###
